sudo: required
services:
        - docker

before_install:
        - docker build -t hadyziade/docker-react -f Dockerfile.dev .

script:
        - docker run hadyziade/docker-react npm run test -- --coverage
